Update patch set 2
Patch Set 2:

It's Skia that now fails perhaps due to fttype1 being dropped.

out/target/product/generic_x86/obj/lib/libdl.so out/target/product/generic_x86/obj/lib/libc.so out/target/product/generic_x86/obj/lib/libm.so -o out/target/product/generic_x86/obj/SHARED_LIBRARIES/libskia_intermediates/LINKED/libskia.so out/target/product/generic_x86/obj/lib/crtend_so.o"
external/skia/src/ports/SkFontHost_FreeType.cpp:520: error: undefined reference to 'FT_Get_PS_Font_Info'
external/skia/src/ports/SkFontHost_FreeType.cpp:1686: error: undefined reference to 'FT_Get_PS_Font_Info'
clang++.real: error: linker command failed with exit code 1 (use -v to see invocation)

Patch-set: 2
Reviewer: jungshik <1060643@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0