Update patch set 1
Patch Set 1:

looks like we'll need to relax the Android.bp slightly:

external/freetype/src/sfnt/sfwoff2.c:314:37: error: unused parameter 'dst' [-Werror,-Wunused-parameter]

Patch-set: 1
Reviewer: Gerrit User 1003224 <1003224@85c56323-6fa9-3386-8a01-6480fb634889>