Update patch set 1
Patch Set 1:

pdfium linking failed because of missing FT_Library_SetLcdFilter, which was a part of ftlcdfil.c that this CL is dropping. 

out/target/product/generic_x86/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--gc-sections -Wl,--hash-style=gnu -Wl,--no-undefined-version -m32  -target i686-linux-android -Bprebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/x86_64-linux-android/bin -Wl,--no-undefined out/target/product/generic_x86/obj/lib/libdl.so out/target/product/generic_x86/obj/lib/libft2.so out/target/product/generic_x86/obj/lib/libc++.so out/target/product/generic_x86/obj/lib/libdl.so out/target/product/generic_x86/obj/lib/libc.so out/target/product/generic_x86/obj/lib/libm.so -o out/target/product/generic_x86/obj/SHARED_LIBRARIES/libpdfium_intermediates/LINKED/libpdfium.so out/target/product/generic_x86/obj/lib/crtend_so.o"
external/pdfium/core/src/fxge/ge/fx_ge_text.cpp:1588: error: undefined reference to 'FT_Library_SetLcdFilter'
clang++.real: error: linker command failed with exit code 1 (use -v to see invocation)

Patch-set: 1
Reviewer: jungshik <1060643@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0